"""DATA_SOURCES.md generation and missing-source reporting."""
from __future__ import annotations

from pathlib import Path

from km.models import Manifest

# source types that satisfy each logical source
_SOURCE_SATISFIED_BY: dict[str, set[str]] = {
    "Twitter/X archive": {"twitter_archive", "twitter_archive_zip"},
    "Google Takeout (Chrome history)": {"takeout_browser", "takeout_zip"},
    "Google My Activity": {"my_activity", "my_activity_html", "takeout_zip"},
    "Chrome history exports": {"chrome_export"},
    "Live Chrome history": {"chrome_live_history"},
    "AI chat exports (ChatGPT/Claude)": {"chat_export"},
    "Reddit GDPR export": {"reddit_gdpr"},
    "Bookmarks": {"chrome_bookmarks", "bookmarks_html", "onetab", "pocket", "pocket_csv", "instapaper"},
}

_INSTRUCTIONS: dict[str, str] = {
    "Twitter/X archive": (
        "X. Settings > Your account > Download an archive of your data. "
        "Takes 1-2 days; you get twitter-<date>.zip containing like.js, tweets.js, account.js. "
        "Note: bookmarks are NOT in the archive, km fetch x-bookmarks scrapes those."
    ),
    "Google Takeout (Chrome history)": (
        "takeout.google.com > Deselect all > select Chrome. "
        "Choose JSON format. You get takeout-<date>.zip with BrowserHistory.json."
    ),
    "Google My Activity": (
        "takeout.google.com > Deselect all > select My Activity. "
        "IMPORTANT: click 'Multiple formats' and set Activity records to JSON. "
        "Include the Gemini Apps product to capture Gemini chats."
    ),
    "Chrome history exports": (
        "Optional: any history-export extension CSV/JSON you already have counts. "
        "km matches history*.csv, chrome*history*.json and similar liberally."
    ),
    "Live Chrome history": (
        "Nothing to request: km reads ~/Library/Application Support/Google/Chrome/*/History "
        "directly (copied first, so a running Chrome is fine)."
    ),
    "AI chat exports (ChatGPT/Claude)": (
        "ChatGPT: Settings > Data controls > Export data (email link, conversations.json inside). "
        "Claude: Settings > Privacy > Export data (also conversations.json, different schema, "
        "km tells them apart by probing the JSON). "
        "Grok: included in the X archive if present, or save a grok.com export and set "
        "grok_export_path in config.yaml."
    ),
    "Reddit GDPR export": (
        "reddit.com/settings/data-request (GDPR request). You get saved_posts.csv and "
        "saved_comments.csv. This complements km fetch reddit, which only sees the most "
        "recent ~1000 saved items."
    ),
    "Bookmarks": (
        "Chrome bookmarks are read automatically. OneTab: Export URLs to a .txt. "
        "Pocket: getpocket.com/export (ril_export.html). Instapaper: Settings > Download CSV."
    ),
}


def missing_report(manifest: Manifest) -> dict[str, bool]:
    found_types = {e.source_type for e in manifest.entries}
    return {
        source: bool(found_types & satisfied_by)
        for source, satisfied_by in _SOURCE_SATISFIED_BY.items()
    }


def write_data_sources_md(manifest: Manifest, path: Path) -> None:
    found = missing_report(manifest)
    lines = [
        "# Data Sources",
        "",
        "Generated by km discover. How to obtain each export, and what was found.",
        "",
    ]
    for source, instructions in _INSTRUCTIONS.items():
        mark = "FOUND" if found.get(source) else "MISSING"
        lines.append(f"## {source} [{mark}]")
        lines.append("")
        lines.append(instructions)
        lines.append("")
    lines.append("## Scraped sources (no export exists)")
    lines.append("")
    lines.append(
        "X bookmarks, Substack saved, and HN favorites/upvoted have no export. "
        "Run km login once, then km fetch x-bookmarks, km fetch substack, km fetch hn."
    )
    path.write_text("\n".join(lines) + "\n")
